os: linux

dist: xenial

branches:
    only:
        - master
    except:
        - dev

jobs:
    include:
        - stage: Backend Tests
          language: php
          php: 7.3
          before_install: cd backend
          before_script:
            - phpenv config-rm xdebug.ini
            - composer self-update
            - composer install
            - touch database/database.sqlite
            - cp .env.travis .env
            - php artisan key:generate
            - php artisan migrate:fresh --force
            - php artisan passport:install
          script: php artisan Test
        - stage: Backend Deploy
          language: php
          php: 7.3
          before_install: cd backend
          script: skip
          deploy:
              provider: heroku
              cleanup: false
              strategy: api
              app: fullstack-penzugy
              api_key:
                  secure: "YDcyEjuwN6TgulflRPI5BLmz/x3PKpV0m83qlV5zxeXOiSEG0KyFdX0IkhcQfqhjlWG9dzPN6djLARXFkmGKz21KYLqrj10W/iv+Snq+0E1mbQVX8WCmzpIElAQ31ciDAk04nBCBW5a/QxBTrmbZDDhSLqJMPpKIWNYo4+hEmhdopUsYd+RA8qtziipa2NvVlX7HQTyfKyh4zmVrD5N3EXELz3aQAulWCfFxjG9oc2ZFKriBeZGAgbni3zV8yJ0zYARodPafwv/WdhSrSEk9o8B+D21oD/SqxXePKMJ0CZZklGgcs+fmdjbsa/Zwa2GXtOaMod6/ALcmPjJD5Ls+xUzjxxSAPUQMhQh7SyY0hX3/rKv3PFxtyYbLI2dBaOViLJMbjatI4mbro2OArsTV4tLsWjbT4ntTbVUvq61VORfdBF2kedIAgdHBn6Z2MOu6rm6xrWbsfQKnRYqE0bq++mtf4iqtCuMn8wPt4/6Vub/KfvdFl2jLHLULiWh3XD4NGTYCb7HzKwQ1gLeGXSSqUwUUuCNVWqG6cS/UIGg5dqsyTzLuJ4GMRRRaPghLg+sve4H8AxjBk2rCE+KgXnZuRWNjV4KT+iyHoS5g9l1/jEz/YcOXtLDkaBL4lnNA4vYqP34VYc3vTbBBh3GHFAicsBbJi9D6aUQoxpkibnvXNT0="
        - stage: Frontend Deploy
          language: node_js
          node_js: node
          cache:
            directories:
              - ./node_modules
          before_install: cd frontend
          install:
            - npm install
          script:
            - npm run build
            - cp dist/fullstack-penzugy/index.html dist/fullstack-penzugy/404.html
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GITHUB_TOKEN
              target_branch: gh-pages
              local_dir: frontend/dist/fullstack-penzugy
              on:
                branch: master
